### ISSUE TITLE
Question: disable navigation criteria

### ISSUE THREAD

**Issue by mistadikay** [staltz/flux-challenge#12]
Hey, didn't find in description what to do when, for example, user scrolled down to the point when only one `jedi` is visible on the top of the list. Should I disable `down`-navigation button in this case while waiting for `apprentice` to load? The same for the `up`-navigation button and `masters`.

**Comment by staltz** [comment]
You choose, but the app should never enter an invalid state, where you are stuck and cannot do anything neither see anything anymore.

**Comment by mistadikay** [comment]
okay, thanks
