### ISSUE TITLE
Observables?

### ISSUE THREAD

**Issue by dralletje** [staltz/flux-challenge#2]
To what extend are observables allowed? I am using observables together with redux a lot now, but I think you don't want observables in this challenge... :p

**Comment by quicksnap** [comment]
I don't see why not; if they compliment Redux well for you, I feel it should be valid.

**Comment by staltz** [comment]
Yep, no problem using those.

> - Must be JavaScript, running as a web page.
> - Preferably a Flux-like architecture, but if you feel like you can use anything
