### ISSUE TITLE
Scrolling constraints in accepted solutions

### ISSUE THREAD

**Issue by sdtsui** [staltz/flux-challenge#46]
Hello André. Interesting challenge.

Clarification on the requirements: 

There are varying degrees of allowable scrolling in the accepted solutions. A consequence: scrolling in one direction very quickly can result in Xendor (the Sith with no master, in the case of scrolling up) being pushed to the bottom of the screen.

This is possible on mynomoto's solution (ClojureScript).
http://puu.sh/lrOfi/fdc3de7bed.png

This is not possible on abaran's solution:
http://puu.sh/lrOkd/518940f4b5.png

nor on staltz's solution
I.e., the last loaded Sith can't go down very far.
http://puu.sh/lrSYI/c50c2065ca.png

So I'd like to confirm: 
What is the condition for the scroll buttons being active?
-At least one sith loaded?
->=2 sith loaded?
-No sith loaded is okay (not in any solutions)?

Do drop me a line in this thread if a test suite for these requirements (and others) would be helpful. **My hunch is that the button should disable when scrolling causes the slots to all be empty (even though mynomoto's solution doesn't do this. Can you confirm? I can modify the readme.**

Thank you,
Dan

**Comment by stinson7** [comment]
I only allow scrolling when the top slot (or bottom slot) is full and has an address for the item above (or below).

**Comment by staltz** [comment]
> What is the condition for the scroll buttons being active?
> **\- At least one sith loaded?**

Is the answer. Empty slots shown are fine (do they anyway while loading).

**Comment by sdtsui** [comment]
@staltz Thank you.
