### ISSUE TITLE
Architecture question about kyldvs submission.

### ISSUE THREAD

**Issue by leftdevel** [staltz/flux-challenge#51]
Hi there.
First than anything, thank you Staltz for making this repo! I've found lots of good things in it.
My question might not be an actual issue, but I found no other way to start a discussion about architecture. If this is the wrong place to ask I'll be happy if the ticket is closed.

My question goes specifically for @kyldvs and his submission. But anybody else's opinion will be more than welcomed.

About his submission: I see that all the components are 'pure', they know nothing about Flux, i.e, they don't make direct use of the Flux Actions, instead they just receive callbacks. Btw, the official TodoApp from Flux site uses Actions directly in the components.

But I feel that receiving callbacks is easier to reason about and also way easier to reuse the components in other apps. An also much easier to test.

My Question is, how do you handle passing callbacks on deeply nested components without that becoming cumbersome and a mess to maintain? For example, 'A' component wraps B component; B wraps C; C wraps D. Then the Container (root) component must pass the callback (e.g myActions.on_D_clicked) to A as a prop, then A to B, then B to C, then C finally passes the callback to D which is the only one actually making use of that callback.

I'm aware about the spread operator in ES6, but I'm not sure if that introduces a new issue, which is hiding the dependencies of the components, making it more difficult to understand what callbacks to pass down to the grand-children components without going to their corresponding class file and inspecting their {propTypes}. But maybe I'm wrong, and this is actually easier to maintain?

Any comments, or any link for reading about the topic would be much appreciated!
Thank you guys!

**Comment by kyldvs** [comment]
As with anything I think there are tradeoffs, and you've identified one of them. I think you summed up the state of things well. If you isolate all Flux interactions to containers and keep your components pure then you get:

Benefits: Easier to reason about, easier to reuse, easier to test, (others?)
Drawbacks: Have to pass callbacks through multiple components, (others?)

In practice we haven't run into that drawback much. Generally the structure is something like

```
FooContainer
 |
FooView
 |
TextInput
```

So it passes from the container to a view, and then the callbacks are usually passed to a very general component. The general component also tends to require a slightly different signature than the callback so it's not a simple prop-passing through anyway. For example, the general component may pass the first param back as an event and you have to extract `event.target.data` or something to pass to the container's callback.

**Comment by kyldvs** [comment]
We also have nested containers within our application, this may break the re-usability of certain components, but it generally helps keep the react tree relatively flat so that we don't have to thread props through many components.

**Comment by leftdevel** [comment]
@kyldvs. Thanks a lot for the thorough response!
Exactly what I needed :)
Wish you guys a great day!
