### ISSUE TITLE
Cancellation if still loading the same row?

### ISSUE THREAD

**Issue by machty** [staltz/flux-challenge#59]
Thanks for putting this together!

I tried @staltz's submission and noticed that if you scrolled while a row is loading, it cancels the AJAX for the row even if it's still in the new scroll view. 

![](http://g.recordit.co/IPTLzCxdif.gif)

I'm taking a stab at a submission so I'd just like to know what the ideal behavior is before I start making it work.

**Comment by staltz** [comment]
Yes, but that request is canceled before anything is sent to the server, so in practice it's just a glitch client-side. You can open the console, with the server process running, to see what requests reach the server. Some other submissions do this too.

**Comment by staltz** [comment]
Or maybe not... I'm seeing other issues going on now. I'll take a look, thanks
